struct Graph;
struct MinHeap;
typedef struct Vertex;
typedef struct VertexNode;
typedef struct Edge;
typedef struct HeapItem;

void createAdjacencyListfromMatrix(Graph undirectedGraph, int adjacencyMatrix[16][16]);
Vertex* createVertex(const int index, const int cost);
void addVertexToList(Vertex* adjacencyList[16], const int index, Vertex* newVertex);
Vertex* getLastLinkedVertex(Vertex* linkedVertex);
void clearLinkedList(Vertex* linkedVertex);
void insertItemToMinHeap(MinHeap minheap, HeapItem item);
int minHeapify(int index, HeapItem* heap[121]);
HeapItem* popHeapItem(MinHeap minheap);
void findMSTUsingKruskalMethod(Graph graph, MinHeap minheap, int adjacencyMatrix[16][16]);
void createMSTSet(int mstEdgeSet[V]);
void createDisjointSets(VertexNode* disjointSets[V]);
void sortEdgeSetAscending(int adjacencyMatrix[V][V]);
int isNotMST(int mstNodes);
Edge* takeMinimumCostEdge();
void relaxDistances(Vertex vertex, Graph graph);